insert into _user (id,
                   created_by,
                   created_date,
                   last_modified_date,
                   name,
                   surname,
                   patronymic,
                   email,
                   password,
                   role,
                   is_enabled)
values (gen_random_uuid(),
        null,
        current_date,
        current_date,
        'admin',
        'admin',
        'admin',
        'admin@mail.ru',
        '$2a$10$Bpck41OehaWlI3/SoVyqUuFvig0LGcPA6mTxXwMDc.8f.xQCuqEva',
        'ADMIN',
        true);