services:
  db:
    image: 'postgres:16'
    container_name: 'farm_track_db'
    environment:
      - 'POSTGRES_DB=farmtrack'
      - 'POSTGRES_PASSWORD=1111'
      - 'POSTGRES_USER=farmadmin'
    ports:
      - '5433:5432'
    volumes:
      - farm:/var/lib/postgresql/data

  app:
    container_name: 'farm_track'
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  farm:
    name: 'farm'