spring:
  datasource:
    url: 'jdbc:postgresql://db:5433/farmtrack'
    username: 'farmadmin'
    password: '1111'
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      "mail.smtp.starttls.enable": ${STARTTLS_ENABLE}

report-service:
  admin-email: ${ADMIN_EMAIL}
