server:
  port: ${SERVER_PORT:8080}
spring:
  docker:
    compose:
      file: compose-prod.yml
  datasource:
    url: jdbc:postgresql://db:5432/farmtrack
    username: farmadmin
    password: 1111
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db.changelog/changelog-master.yml

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      "mail.smtp.starttls.enable": ${STARTTLS_ENABLE}

report-service:
  admin-email: ${ADMIN_EMAIL}
